# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    form.type.images:
            class: AppBundle\Form\Type\FileCollectionType
            tags:
                - { name: form.type, alias: files }

    form.type.image:
        class: AppBundle\Form\Type\FileType
        tags:
            - { name: form.type, alias: appbundle_file }

    form.type.authors:
        class: AppBundle\Form\Type\AuthorCollectionType
        tags:
            - { name: form.type, alias: authors }

    form.type.author:
        class: AppBundle\Form\Type\AuthorType
        tags:
            - { name: form.type, alias: appbundle_author }